// _id: 6305083f3fed5eee128f86a3
// the _id is generated by the MonogoDb driver
// the Driver -> MongoDb : this makes it scalable as each driver can generate the _id
// 12 bytes each 2 characters is a byte 
    // first 4 bytes: timestamp
    // next 3 bytes : machine identifier
    // next 2 bytes : process identifier
    // last 3 bytes : counter

    // 1 byte = 8 bits
    // 2 ^ 8 = 256 
    // 2 ^ 24 = 16M

const mongoose = require('mongoose');

const id = new mongoose.Types.ObjectId();
console.log(id);
console.log(id.getTimestamp());

const isValid = mongoose.Types.ObjectId.isValid('12345');
console.log(isValid);